version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: secureapp_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: secureapp
      POSTGRES_PASSWORD: secureapp
      POSTGRES_DB: secureapp
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: secureapp_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db_data: